---

# Assumptions:
# - systemd
# - `syncthing` package; ships with systemd configuration
#
# Tested on:
# - Raspberry Pi OS Lite 2020-12-02 (Raspbian/Debian Buster)

- name: Install and configure Syncthing
  hosts: syncthing
  become: yes

  tasks:
    - name: Define public key
      # upstream at https://syncthing.net/release-key.gpg
      ansible.builtin.copy:
        dest: /usr/share/keyrings/syncthing-archive-keyring.gpg
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        src: syncthing-release-key.gpg

    - name: Define dedicated APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/syncthing.list
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        content:
          deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg]
          https://apt.syncthing.net/ syncthing stable

    - name: Define dedicated APT repository
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/syncthing
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        content: |
          Package: *
          Pin: origin apt.syncthing.net
          Pin-Priority: 990

    - name: Install Syncthing
      ansible.builtin.package:
        name: syncthing
        state: latest
        install_recommends: false

    - name: Create the service group ({{ syncthing_user }})
      ansible.builtin.group:
        name: '{{ syncthing_group }}'
        state: present
        system: yes

    - name: Create the service user ({{ syncthing_user }})
      ansible.builtin.user:
        name: '{{ syncthing_user }}'
        group: '{{ syncthing_group }}'
        system: yes

    - name: Configure fs.inotify.max_user_watches
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: "{{ fs_inotify_max_user_watches }}  # Force YAML string but not sysctl string"

    - name: Enable Syncthing service on boot
      ansible.builtin.service:
        name: syncthing@{{ syncthing_user }}.service
        enabled: yes

    - name: (Re-)Start Syncthing service
      ansible.builtin.service:
        name: syncthing@{{ syncthing_user }}.service
        state: restarted
